version: "3.1"

services:
  nginx:
    image: nginx
    networks:
      boocam-wiki-net:
        ipv4_address: 172.16.238.11
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx/build:/usr/share/nginx/html
      - ./nginx/nginx:/etc/nginx
  pm2:
    image: keymetrics/pm2
    networks:
      boocam-wiki-net:
        ipv4_address: 172.16.238.12
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - ./node/dist:/dist
    environment:
      - DB_PORT=
      - DB_HOST=
      - DB_PASS=
      - DB_USER=
      - DB_DB=
      - PORT=
      - IMG_BUCKET_NAME=
      - IMG_STORAGE_ENDPOINT=https://kr.object.ncloudstorage.com
      - ACCESS_KEY=
      - SECRET_KEY=
    command: sh -c "pm2 start /dist/app.js -f -i max && tail -f /dev/null"

networks:
  boocam-wiki-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
